### PR TITLE
Feature/issue 177 setup swagger

### PR DESCRIPTION
**Pull request by rasmus-storjohann-PG**

### CODE REVIEW

**Comment by rasmus-storjohann-PG** [comment]
@bensinjin this is work in progress, not yet ready for review. You may notice that it restructures the sorting code quite a bit, but I'll be happy to let you merge in the proximity sort stuff first.

**Comment by bensinjin** [comment]
Cool sounds good.

**Comment by rasmus-storjohann-PG** [comment]
If you go to https://fierce-ravine-89308-pr-189.herokuapp.com/swagger/ and make a call to /services/ with no argument, you'll see a 500 error. Can you have a look at the error message and let me know any insights you might have about what the problem could be?

**Comment by bensinjin** [comment]
This is looking sensible. I've reviewed the commits but am not really as familiar with DRF as I should so I may find things to improve as I pull in my proximity search work.

**Pull request merged**
